laravel/routes/web.php
<?php

use App\Http\Controllers\Order\OrderController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Services\WebCheckOut\{PaymentService,AuthService};
use Carbon\Carbon;
use Illuminate\Http\Client\Request as ClientRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login');
Auth::routes();
/*---------------------------------------------------
                 Public Route
------------------------------------------------------- */
route::group([ 'middleware' => ['auth','verified']],function(){
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::get('transactions',[TransactionController::class,'index'])->name('transaction.index');
    Route::get('transactions/{transaction}/resume',[TransactionController::class,'show'])->name('transaction.resume');
    Route::resource('order',OrderController::class);
    Route::get('order/resume/{order}',[OrderController::class,'resume'])->name('order.resume');

});

laravel/app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
/**
 * MODEL DE ORDER
 */
class Order extends Model
{
    use HasFactory;

    protected $fillable=[
        'customer_name',
        'customer_email',
        'customer_mobile',
        'status',
    ];

    protected $casts=[
        'status'=>'string'
    ];

    public function transaction():HasOne
    {
        return $this->hasOne(\App\Models\Transaction::class);
    }
}

laravel/app/Models/Transaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * MODEL DE TRANSACCION
 */
class Transaction extends Model
{
    use HasFactory;

    protected $fillable =[
        'status',
        'reason',
        'message',
        'date',
        'requestId',
        'processUrl',
        'order_id',
    ];

    public function order():BelongsTo{
     return $this->belongsTo(\App\Models\Order::class);
    }
}

laravel/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel/app/Http/Controllers/Order/OrderController.php
<?php

namespace App\Http\Controllers\Order;

use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Repositories\Order\OrderRepository;
use App\Http\Requests\Order\CreateOrderRequest;
use App\Repositories\Transaction\TransactionRepository;
use App\Responsable\Order\{OrderCreateResponsable,OrderIndexResponsable,OrderResumeResponsable};
use App\Services\PaymentMethod\GlobalService;
use App\Services\Transaction\GenerateTransactionService;
use App\Services\WebCheckOut\PaymentService;
use Exception;

class OrderController extends Controller
{
    private $repository;
    private $transactionRepository;
    public function __construct(OrderRepository $repository,TransactionRepository $transactionRepository)
    {
        $this->repository = $repository;
        $this->transactionRepository = $transactionRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(OrderIndexResponsable $orderIndexResponsable)
    {
        return $orderIndexResponsable;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(OrderCreateResponsable $orderCreateResponsable)
    {
        return $orderCreateResponsable;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     * creo inicialmente la order y le asocio la respuesta de placeToPay y lo guardo como una transaccion
     */
    public function store(CreateOrderRequest $request)
    {
        try{
            DB::beginTransaction();
            $order =  $this->repository->create($request->all());
            // Use Strategy
                $response=GlobalService::take($request,$order,(object)[
                    'transactionRepository'=>$this->transactionRepository,
                    'orderRepository'=>$this->repository
                ])->response;
               DB::commit();
                if(isset($response->transaction)){
                    return new OrderResumeResponsable($order);
                }
            throw new Exception("Error Processing Request", 1);
        } catch (\Throwable $e) {
            DB::rollback();
            return redirect()->back()->withErrors(['error' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    /**
     *Creation of the purchase summary
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function resume(Order $order)
    {
       return new OrderResumeResponsable($order);
    }
}

laravel/app/Http/Controllers/Transaction/TransactionController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Http\Controllers\Controller;
use App\Models\Transaction;
use App\Responsable\Transaction\TransactionIndexResponsable;
use App\Responsable\Transaction\TransactionShowResponsable;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    public function index(TransactionIndexResponsable $transactionIndexResponsable)
    {
        return $transactionIndexResponsable;
    }

    public function show(Transaction $transaction)
    {


        return new TransactionShowResponsable($transaction);
    }


}

laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" xml:lang="{{ app()->getLocale() }}" xmlns="http://www.w3.org/1999/xhtml">
{{--<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">--}}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @guest
    @else
        <meta name="user" content="{{ Auth::user()->id }}">
    @endguest
<!--OpenGraph metadata-->
    @include('layouts.partials.css')
    @stack('css')
    @stack('scripts-up')
    {{--FAVICON--}}

    {{--LDJSON--}}
    {{-- @include('layouts.partials.ldjson')
 --}}
    {{--Google analitycs--}}
{{--     @include('layouts.partials.google')
 --}}
    <title>{{ config('app.name') }}</title>
</head>

<body class="p-0">
<main class="">
    @auth
        @include('layouts.partials.navbar')
    <header>
        @include('layouts.partials.sidebar')

        @stack('header-plus')
    </header>
    @endauth

<div id="content" class="content py-3" >
    @yield('content')
</div>
{{-- footer --}}
    {{-- @include('admin.layouts.partials.footer') --}}

</main>
@include('layouts.partials.js')
@stack('scripts-down')
</body>

</html>

laravel/resources/views/layouts/partials/css.blade.php
<link rel="stylesheet" href="{{asset('css/app.css')}}">

laravel/resources/views/layouts/partials/errors.blade.php
@if(!empty($errors))
    @if($errors->any())
        <ul class="alert alert-danger" style="list-style-type: none">
            @foreach($errors->all() as $error)
                <li>{!! $error !!}</li>
            @endforeach
        </ul>
    @endif
@endif

laravel/resources/views/layouts/partials/js.blade.php
<script src="{{asset('js/app.js')}}"></script>

laravel/resources/views/layouts/partials/navbar.blade.php
<nav class="navbar navbar-top navbar-expand border-bottom bg-white">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <img src="{{asset('img/logo.jpg')}}" width="250" height="75" alt="evertec">
            {{------------------- Navbar Nav Start -----------------------}}
            <ul class="navbar-nav align-items-center ml-md-auto">
                <li class="nav-item d-xl-none">

                    {{------------------- Sidenav toggler -----------------------}}
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>


            </ul>
            {{--------------***** Navbar Nav End *****------------------}}

            {{------------------- Navbar Nav Start -----------------------}}
            <ul class="navbar-nav align-items-center ml-auto ml-md-0">
                <li class="nav-item dropdown">

                    {{------------------------------------------}}
                    <a class="nav-link pr-0" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                        <div class="media align-items-center">

                            <div class="media-body ml-2 d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold text-dark">{{ Auth::user()->email }} ^</span>
                            </div>

                        </div>

                    </a>

                    {{------------------------------------------}}
                    <div class="dropdown-menu dropdown-menu-right">

                        {{------------------------------------------}}
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Bienvenido!</h6>
                        </div>

                        {{------------------------------------------}}


                        {{------------------------------------------}}
                        <div class="dropdown-divider"></div>

                        {{------------------------------------------}}
                        <a href="javascript:void(0);" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out text-red">
                                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                <polyline points="16 17 21 12 16 7"></polyline>
                                <line x1="21" y1="12" x2="9" y2="12"></line>
                            </svg>
                            <span>Salir</span>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </a>

                    </div>
                </li>
            </ul>
            {{--------------***** Navbar Nav End *****------------------}}

        </div>
    </div>
</nav>

laravel/resources/views/layouts/partials/sidebar.blade.php
<ul class="nav">
    <li class="nav-item">
      <a class="nav-link active" href="{{route('order.create')}}">New order</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{route('order.index')}}">List Order</a>
    </li>
    @if(Auth::user()->is_admin)
    <li class="nav-item">
      <a class="nav-link " href="{{route('transaction.index')}}">Transactions</a>
    </li>
    @endif
  </ul>

laravel/resources/views/order/create.blade.php
@extends('layouts.app')
@section('content')
<!-- Breadcrumb -->
{{-- @include('admin.layouts.partials.breadcrumb', ['inicio' => 'Inicio','path' => 'Crear']) --}}
<!-- begin page-header -->
<!------------------- Content Wrapper Start ----------------------->
<div class="container-fluid mb-5" >
    <div class="row justify-content-center">
        <div class="col-md-6 col-12">
            <div class="card-wrapper">
                <!-- Custom form validation -->
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header ">
                        <h3 class="mb-0">Procesos De Checkout</h3>
                    </div>

                    <!-- Card body -->
                    <div class="card-body">
                        @include('layouts.partials.errors')
                        <form action="{{route('order.store')}}" method="POST">
                            @csrf
                            @include('order.fields')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/order/fields.blade.php
<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="text-center">
            <h4>Products</h4>
            <div class="card">
                <img class="card-img-top" src="{{asset('img/shoes.jpg')}}" alt="Card image cap">
                <div class="card-body">
                    <p>Adidas Bravada Shoes - Black | adidas US</p>
                    <div class="d-flex justify-content-end">
                        <p class="text-right font-weight-bold">Price: <span>{{env('PRICE_ARTICLE')}}</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h4>Personal information</h4>
        </div>
        <div class="col-md-6 col-12 p-2">
            <label for="" class="fomr-control-label">{{__('Name')}}</label>
            <input type="text" class="form-control" id="customer_name" value="{{old('customer_name')}}" placeholder="name" minlength="3" maxlength="70"  name="customer_name"  required>
        </div>
        <div class="col-md-6 col-12 p-2">
            <label for="" class="fomr-control-label">{{__('Email')}}</label>
            <input type="email" class="form-control" value="{{old('customer_email')}}" placeholder="example@example.com"  minlength="5" maxlength="70" name="customer_email" required>
        </div>
        <div class="col-md-6 col-12 p-2">
            <label for="" class="fomr-control-label">{{__('Phone')}}</label>
            <input type="text" class="form-control" minlength="7" maxlength="30" placeholder="(999) 9999-9999" id="customer_mobile" value="{{old('customer_mobile')}}" name="customer_mobile" required>
        </div>
        <div class="col-md-6 col-12 p-2">
            <label for="" class="fomr-control-label">{{__('Payment Method')}}</label>
            <select name="type" class="form-control" id="" required>
                <option value="1">PlaceToPay</option>
            </select>
        </div>
        <div class="col-md-6 col-12 p-2">
            <label for="" class="fomr-control-label">{{__('Price')}}</label>
            <input type="text" class="form-control text-right" value="{{env('PRICE_ARTICLE')}}" name="price" required readonly>
        </div>
    </div>


    <div class="d-flex justify-content-end">
        <button class="btn btn-success" type="submit">Procesar</button>
    </div>
</div>
@push('scripts-down')
<script type="text/javascript" src="{{ asset('js/inputmask/jquery.inputmask.js')}}"></script>
<script>
    $("#customer_mobile").inputmask({"mask": "(999) 999-9999",'removeMaskOnSubmit': true});
</script>
@endpush

laravel/resources/views/order/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Breadcrumb -->
{{-- @include('admin.layouts.partials.breadcrumb', ['inicio' => 'Inicio','path' => 'Crear']) --}}
<!-- begin page-header -->
<!------------------- Content Wrapper Start ----------------------->
<div class="container-fluid mb-5" >
    <div class="row justify-content-center">
        <div class="col-md-8 col-12">
            <div class="card-wrapper">
                <!-- Custom form validation -->
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header ">
                        <div class="d-flex justify-content-between">
                            <h3 class="mb-0">Lists Order</h3>
                            <a class="btn btn-sm btn-primary" href="{{route('order.create')}}">New Order</a>
                        </div>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                        @include('order.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/order/resume.blade.php
@extends('layouts.app')
@section('content')

<!------------------- Content Wrapper Start ----------------------->
<div class="container-fluid mb-5" >
    <div class="row justify-content-center">
        <div class="col-md-6 col-12">
            <div class="card-wrapper">
                <!-- Custom form validation -->
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header ">
                        <h3 class="mb-0">Resumen</h3>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">

                        <form action="{{route('order.store')}}" method="POST">
                            @csrf
                            <div class="container mb-5">
                                <div class="row justify-content-center">
                                    <div class="text-center">
                                        <h4>Product: <span class="text-primary">Adidas Bravada</span></h4>
                                        <div class="card">
                                            <img class="card-img-top" src="{{asset('img/shoes.jpg')}}" alt="Card image cap">
                                            <div class="card-body">
                                                <p>Adidas Bravada Shoes - Black | adidas US</p>
                                                <div class="d-flex justify-content-end">
                                                    <p class="text-right font-weight-bold">Price: <span>{{env('PRICE_ARTICLE')}}</span></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row p-3">
                                    <div class="col-12">
                                        <h4>Personal information</h4>
                                    </div>
                                    <div class="col-md-6 col-12 p-2">
                                        <label for="" class="form-control-label">{{__('Name')}}</label>
                                        <label for="" class="form-control">{{$order->customer_name}}</label>
                                    </div>
                                    <div class="col-md-6 col-12 p-2">
                                        <label for="" class="form-control-label">{{__('Email')}}</label>
                                        <label for="" class="form-control">{{$order->customer_email}}</label>
                                    </div>
                                    <div class="col-md-6 col-12 p-2">
                                        <label for="" class="form-control-label">{{__('Phone')}}</label>
                                        <label for="" class="form-control">{{$order->customer_mobile}}</label>
                                    </div>
                                    <div class="col-md-6 col-12 p-2">
                                        <label for="" class="form-control-label">{{__('Status Pay')}}</label>
                                        <label for="" class="form-control">{{$order->status}}</label>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-end">
                                    <a class="btn btn-danger mr-2" href="{{route('order.index')}}">Back</a>
                                        @if($order->status=="REJECTED")
                                            <a class="btn btn-success" href={{route('order.create')}}>Retry</a>
                                        @elseif($order->status=="CREATED" || $order->status=='PENDING')
                                            <a class="btn btn-success" href={{$order->transaction->processUrl}}>Process Payment</a>
                                        @else
                                        <span class="font-weight-bold text-sucess text-green btn">Order Paid</span>

                                    @endif

                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/order/table.blade.php
<table class="table table-responsive">
    <thead>
        <th width="5%">{{__('Option')}}</th>
        <th width="10%">{{__('Name')}}</th>
        <th width="10%">{{__('Email')}}</th>
        <th width="5%">{{__('Mobile')}}</th>
        <th width="5%">{{__('Status')}}</th>
        <th width="10%">{{__('Created at')}}</th>

    </thead>
    <tbody>
        @foreach ($orders as $order )
        <tr>
            <td>
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                    <a type="button" class="btn btn-outline-success" href="{{route('order.resume',$order->id)}}">Resume</a>
                  </div>
            </td>
            <td>{{$order->customer_name}}</td>
            <td>{{$order->customer_email}}</td>
            <td>{{$order->customer_mobile}}</td>
            <td class=" font-weight-bold {{($order->status == "REJECTED")?'text-danger':''}}">{{$order->status}}</td>
            <td>{{Carbon\Carbon::parse($order->created_at)->format('d/m/Y H:m')}}</td>
        </tr>
        @endforeach

    </tbody>
</table>
<div class="d-flex justify-content-center">
    {{$orders->links()}}
</div>

laravel/resources/views/transactions/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Breadcrumb -->
<!-- begin page-header -->
<!------------------- Content Wrapper Start ----------------------->
<div class="container-fluid mb-5" >
    <div class="row justify-content-center">
        <div class="col-md-7 col-12">
            <div class="card-wrapper">
                <!-- Custom form validation -->
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header ">
                        <div class="d-flex justify-content-between">
                            <h3 class="mb-0">Lists Transactions</h3>
                        </div>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                        @include('transactions.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/transactions/resume.blade.php
@extends('layouts.app')
@section('content')

<!------------------- Content Wrapper Start ----------------------->
<div class="container-fluid mb-5" >
    <div class="row justify-content-center">
        <div class="col-md-8 col-12">
            <div class="card-wrapper">
                <!-- Custom form validation -->
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header ">
                        <h3 class="mb-0">Resumen</h3>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                         <div class="container">
                             <div class="row">
                                <div class="col-md-4 col-12">
                                    <label for="" class="form-control-label">{{__('RequestId')}}</label>
                                    <label for="" class="form-control">{{$transaction->requestId}}</label>
                                </div>
                                <div class="col-md-4 col-12">
                                    <label for="">{{__('Status')}}</label>

                                    <label for="" class="form-control">{{$transaction->status->status}}</label>
                                </div>
                                <div class="col-md-4 col-12">
                                    <label for="">{{__('Name')}}</label>

                                    <label for="" class="form-control">{{$transaction->request->payer->name}}</label>
                                </div>
                                <div class="col-md-4 col-12">
                                    <label for="" class="form-control-label">{{__('Email')}}</label>

                                    <label for="" class="form-control">{{$transaction->request->payer->email}}</label>
                                </div>
                                <div class="col-md-4 col-12">
                                    <label for="" class="form-control-label">{{__('Mobile')}}</label>
                                    <label for="" class="form-control">{{$transaction->request->payer->mobile}}</label>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col-md-4 col-12">
                                    <label for="" class="form-control-label">{{__('Payment')}}</label>
                                    <label for="" class="form-control">{{$transaction->request->payment->reference}}</label>
                                </div>
                                <div class="col-md-4 col-12">
                                    <label for="" class="form-control-label">{{__('Description')}}</label>
                                    <label for="" class="form-control">{{$transaction->request->payment->description}}</label>
                                </div>
                                <div class="col-md-4 col-12">
                                    <label for="" class="form-control-label">{{__('Total')}}</label>
                                    <label for="" class="form-control">{{$transaction->request->payment->amount->total }} {{$transaction->request->payment->amount->currency }}</label>
                                </div>
                             </div>
                         </div>



                        <div class="d-flex justify-content-end">
                            <a href="{{route('transaction.index')}}" class="btn btn-danger">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/transactions/table.blade.php
<table class="table table-responsive">
    <thead>
        <th>{{__('Option')}}</th>
        <th>{{__('Id Transaction')}}</th>
        <th>{{__('Status')}}</th>
        <th>{{__('Message')}}</th>
        <th>{{__('Nro Order')}}</th>

        <th>{{__('Date')}}</th>

    </thead>
    <tbody>
        @foreach ($transactions as $transaction )
        <tr>
            <td>
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                    <a type="button" class="btn btn-outline-success" href="{{route('transaction.resume',$transaction->id)}}">Resume</a>
                  </div>
            </td>
            <td>{{$transaction->requestId}}</td>
            <td class="">{{$transaction->status}}</td>
            <td>{{$transaction->message}}</td>
            <td>{{$transaction->order_id}}</td>
            <td>{{$transaction->date}}</td>
        </tr>
        @endforeach

    </tbody>
</table>
<div class="d-flex justify-content-center">
    {{$transactions->links()}}
</div>